# yaml-language-server: $schema=https://raw.githubusercontent.com/codemod/codemod/refs/heads/main/schemas/workflow.json

version: "1"

params:
  schema:
    commit_per_step:
      type: boolean
      default: false
      description: Commit after each change-producing step with a meaningful message
    run_ai_step:
      type: boolean
      default: false
      description: Run AI step for closure-dependent tricky cases
    publish_pr:
      type: boolean
      default: false
      description: Push branch and create PR (off by default)
    main_branch:
      type: string
      default: "main"
      description: Target branch for PR
    api_token:
      type: string
      description: GitHub API token when gh CLI unavailable
      secret: true
    pr_title:
      type: string
      description: Optional PR title
    pr_body:
      type: string
      description: Optional PR body
      multi_line: true

nodes:
  - id: apply-transforms
    name: Apply AST Transformations
    type: automatic
    steps:
      - name: "Hoist nested React components"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "tsx"
          semantic_analysis: workspace
          include:
            - "**/*.tsx"
            - "**/*.jsx"
          exclude:
            - "**/node_modules/**"
            - "**/vendor/**"
            - "**/*.test.*"
            - "**/*.spec.*"
            - "**/__pycache__/**"
      - name: "Commit AST transformations"
        run: |
          git add -A
          [ -n "$(git status --porcelain)" ] && git commit -m "fix: hoist nested React components to module scope" || true
        if: params.commit_per_step

  - id: ai-tricky-cases
    name: AI Tricky Cases
    type: automatic
    depends_on: [apply-transforms]
    steps:
      - name: "AI step for closure-dependent cases"
        if: params.run_ai_step
        ai:
          prompt: |
            You are performing a React code migration. Modify files directly.

            Goal: Resolve closure-dependent nested components that were flagged by the codemod.

            Handle these cases:
            1. Components with `// codemod: closure-dependent` comment — hoist to module scope and pass outer vars as props.
            2. Ensure prop types/interfaces are added if needed.
            3. Preserve behavior and formatting.

            Constraints: Add TODO if unsure; keep existing logic intact.
      - name: "Commit AI fixes"
        run: |
          git add -A
          [ -n "$(git status --porcelain)" ] && git commit -m "fix: AI-assisted resolution of closure-dependent nested components" || true
        if: params.commit_per_step

  - id: publish
    name: Publish
    type: automatic
    depends_on: [ai-tricky-cases]
    steps:
      - name: "Push branch to remote"
        run: |
          BRANCH=$(git branch --show-current)
          git push -u origin "$BRANCH"
        if: params.publish_pr
      - name: "Create PR to main branch"
        run: |
          BRANCH=$(git branch --show-current)
          BASE="${PARAM_MAIN_BRANCH:-main}"
          TITLE="${PARAM_PR_TITLE:-fix: hoist nested React components to module scope}"
          BODY="${PARAM_PR_BODY:-Automated codemod: hoist nested React components.}"
          [ -n "$PARAM_API_TOKEN" ] && export GITHUB_TOKEN="$PARAM_API_TOKEN"
          gh pr create --base "$BASE" --head "$BRANCH" --title "$TITLE" --body "$BODY"
        if: params.publish_pr
